#!/bin/bash

# This script is designed to generate a Minecraft launcher for Linux user.
# This script is under MIT License, feel it free to modify this script.
# Tested on my PC with Ubuntu 12.10 64 bits.

# Visit: https://github.com/lisposter/Minecraft-Toolbox  for more information.

clear
echo ""
echo "#*************************************************#" 
echo "#         Minecraft Launcher Generater            #"
echo "#            By lisposter(Leigh Zhu)              #"
echo "#-------------------------------------------------#"
echo "#                version 2.0                      #"
echo "#            twitter: @lisposter                  #"
echo "#              email: i@zhuli.me                  #"
echo "#                 MIT License                     #"
echo "#*************************************************#" 
echo ""
echo ""

# config default
MCPATH=/home/$(whoami)/.minecraft


if [ ! -e $MCPATH/Minecraft.jar ]; then
    mkdir -p $MCPATH
    wget -P $MCPATH https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar
fi

cat > $MCPATH/mcl.sh<<EOF
#!/bin/bash
# This file is generated by mcl-gen.sh.
# Visit: https://github.com/lisposter/Minecraft-Toolbox  for more information.

java -jar ${MCPATH}/Minecraft.jar
EOF

chmod +x $MCPATH/mcl.sh
sudo rm -rf /usr/bin/minecraft
sudo ln -s $MCPATH/mcl.sh /usr/bin/minecraft

cat > $HOME/.local/share/applications/minecraft.desktop<<EOF
[Desktop Entry]
Name=Minecraft
GenericName=Sandbox Game by Mojang
Comment=Play Minecraft
Exec=minecraft
Terminal=false
Type=Application
Icon=$MCPATH/assets/icons/icon_32x32.png
Categories=Game;
EOF

clear
echo "#*************************************************#" 
echo "#     Minecraft Launcher has been Installed!      #"
echo "#                 Happy Mining!!                  #"
echo "#=================================================#"
echo "#                                                 #"
echo "#         ## Two ways to run Minecraft:           #"
echo "#     1. Type 'minecraft' in your Terminal.       #"
echo "#     2. Open Unity Dash, search 'Minecraft'.     #"
echo "#                                                 #"
echo "#                                                 #"
echo "#*************************************************#"