#!/bin/bash

# This script is designed to generate a Minecraft launcher for Linux user.
# This script is under MIT License, feel it free to modify this script.
# Tested on my PC with Ubuntu 12.10 64 bits.

# Visit: https://github.com/lisposter/Minecraft-Toolbox  for more information.

clear
echo ""
echo "#*************************************************#" 
echo "#         Minecraft Launcher Generater            #"
echo "#            By lisposter(Leigh Zhu)              #"
echo "#-------------------------------------------------#"
echo "#                version 1.0                      #"
echo "#            twitter: @lisposter                  #"
echo "#              email: i@zhuli.me                  #"
echo "#                 MIT License                     #"
echo "#*************************************************#" 
echo ""
echo ""

MCPATH=$HOME/.minecraft
if [ ! -e $MCPATH/bin/minecraft.jar ]; then
	echo -ne "Seems that your Minecraft isn't installed correctly." 
fi

echo "Now, you should set size of memory for java."
echo "==========================================================="
echo "According to the thread of Optifine on Minecraft forum,"
echo "Minecraft didn't need more than 512MB."
echo "==========================================================="


echo "Now, please input the minimum size of memory for java:"
read MinMem

echo "And, the maximum size of memory for java:"
read MaxMem

echo "Please input your login name:"
read LoginName

echo "Finally, input your password (leave blank for play offline):"
read PassWord

cat > $MCPATH/mcl.sh<<EOF
#!/bin/bash
# This file is generated by mcl-gen.sh.
# Visit: https://github.com/lisposter/Minecraft-Toolbox  for more information.

MCPATH=$HOME/.minecraft
cd $MCPATH/bin/
java -Xms${MinMem}M -Xmx${MaxMem}M -classpath jinput.jar:lwjgl.jar:lwjgl_util.jar:minecraft.jar -Djava.library.path="$MCPATH/bin/natives/" net.minecraft.client.Minecraft "$LoginName" "$PassWord"
EOF

chmod +x $MCPATH/mcl.sh
sudo rm -rf /usr/bin/minecraft
sudo ln -s $MCPATH/mcl.sh /usr/bin/minecraft

if [ ! -e $MCPATH/Grass.png ]; then
	wget -P $MCPATH/ http://media-mcw.cursecdn.com/c/c5/Grass.png 
fi

cat > $HOME/.local/share/applications/minecraft.desktop<<EOF
[Desktop Entry]
Name=Minecraft
GenericName=Sandbox Game
Comment=Play Minecraft
Exec=minecraft
Terminal=false
Type=Application
StartupNotify=true
Icon=${MCPATH}/Grass.png
Categories=Game;
Actions=OpenDotMinecraft

[Desktop Action OpenDotMinecraft]
Name=Open .minecraft
Exec=nautilus ${MCPATH}
OnlyShowIn=Unity;
EOF


sudo mv ./mcl-gen.sh ${MCPATH}

clear
echo "#*************************************************#" 
echo "#     Minecraft Launcher has been Generated!      #"
echo "#                 Happy Mining!!                  #"
echo "#=================================================#"
echo "#                                                 #"
echo "#         ## Two ways to run Minecraft:           #"
echo "#     1. Type 'minecraft' in your Terminal.       #"
echo "#     2. Open Unity Dash, search 'Minecraft'.     #"
echo "#                                                 #"
echo "#  If you want to change login info. Run again.   #"
echo "#  ==  Location: ~/.minecraft/mcl-gen.sh          #"
echo "#                                                 #"
echo "#*************************************************#"

